local l_script_FirstAncestor_0 = script:FindFirstAncestor("FindReplaceAll");
return require(l_script_FirstAncestor_0.Packages.Framework).Styling.createStyleSheet("FindReplaceAllLightTheme", {}, {
    ExpandReplaceInput = "rbxasset://studio_svg_textures/Shared/Navigation/Light/Standard/Expand.png", 
    CollapseReplaceInput = "rbxasset://studio_svg_textures/Shared/Navigation/Light/Standard/Collapse.png", 
    MatchCase = "rbxasset://studio_svg_textures/Lua/FindReplaceAll/Light/Standard/MatchCase.png", 
    ClearInput = "rbxasset://studio_svg_textures/Lua/FindReplaceAll/Light/Standard/ClearInput.png", 
    MatchWholeWord = "rbxasset://studio_svg_textures/Lua/FindReplaceAll/Light/Standard/MatchWholeWord.png", 
    RegularExpression = "rbxasset://studio_svg_textures/Lua/FindReplaceAll/Light/Standard/RegularExpression.png", 
    FindPrevious = "rbxasset://studio_svg_textures/Lua/FindReplaceAll/Light/Standard/FindPrevious.png", 
    FindNext = "rbxasset://studio_svg_textures/Lua/FindReplaceAll/Light/Standard/FindNext.png", 
    Filter = "rbxasset://studio_svg_textures/Shared/Utility/Light/Standard/Filter.png"
});