local l_script_FirstAncestor_0 = script:FindFirstAncestor("CompositorDebugger");
return require(l_script_FirstAncestor_0.Packages.Framework).Styling.createStyleSheet("CompositorDebuggerDarkTheme", {}, {
    InactiveLayer = Color3.fromHex("#565656"), 
    ActiveLayer = Color3.fromHex("#E1E1E1"), 
    LayerHover = Color3.fromHex("#424242"), 
    ActiveTimeBar = Color3.fromHex("#008BDB"), 
    InactiveTimeBar = Color3.fromHex("#565656"), 
    HistoryLegend1 = Color3.fromHex("#F98B58"), 
    HistoryLegend2 = Color3.fromHex("#0ADE52"), 
    HistoryLegend3 = Color3.fromHex("#1AC8FF"), 
    AdornmentDot1 = Color3.fromHex("#FDEBAC"), 
    AdornmentDot2 = Color3.fromHex("#FFAE3E"), 
    AdornmentDot3 = Color3.fromHex("#F98B58"), 
    AdornmentDot4 = Color3.fromHex("#FF62C0"), 
    AdornmentDot5 = Color3.fromHex("#D65AFC"), 
    AdornmentDot6 = Color3.fromHex("#1AC8FF"), 
    AdornmentDot7 = Color3.fromHex("#3BF2B1"), 
    AdornmentDot8 = Color3.fromHex("#0ADE52"), 
    AdornmentDot9 = Color3.fromHex("#95FF0F"), 
    AdornmentDot10 = Color3.fromHex("#DBFF66"), 
    AdornmentDot11 = Color3.fromHex("#FBFF3E")
});