local l_Parent_0 = script.Parent.Parent.Parent.Parent;
local _ = require(l_Parent_0.Src.Types);
local v2 = {
    FailedUrl = "FailedUrl", 
    FailedToImportMap = "FailedToImportMap", 
    FailedToUploadFromFileMap = "FailedToUploadFromFileMap", 
    FailedToUploadTooLarge = "FailedToUploadTooLarge", 
    FailedToInsertAssetManager = "FailedToInsertAssetManager", 
    MissingMaterial = "MissingMaterial", 
    None = "None"
};
return function() --[[ Line: 16 ]]
    -- upvalues: v2 (copy)
    return v2;
end;