local l_script_FirstAncestor_0 = script:FindFirstAncestor("CompositorDebugger");
local _ = require(l_script_FirstAncestor_0.Src.Types);
return {
    children = {
        [1] = {
            children = {
                [1] = {
                    children = {
                        [1] = {
                            children = {}, 
                            className = "ClipLayer", 
                            id = "{91a192be-2369-41cb-801a-26bd4fc053d2}", 
                            name = "Tool None", 
                            props = {
                                animationId = "rbxassetid://507768375", 
                                didLoopEventName = "", 
                                endTime = 1e999, 
                                looping = -1, 
                                markerEvents = {}, 
                                preload = true, 
                                speed = 1, 
                                startTime = 0, 
                                timePositionEvents = {}
                            }, 
                            state = {
                                currentAnimationId = "rbxassetid://507768375", 
                                length = 0.0416666679084301, 
                                loadingState = "Loaded", 
                                markerEvents = {}, 
                                prevTimePosition = 0.03333350596949458, 
                                timePosition = 0.03333350596949458, 
                                timePositionEvents = {}, 
                                timePositionNormalized = 0.8000041194258892
                            }, 
                            weight = 1
                        }, 
                        [2] = {
                            children = {
                                [1] = {
                                    children = {
                                        [1] = {
                                            children = {}, 
                                            className = "RestPose", 
                                            id = "{b93312c4-8c4d-453c-93ed-9541195b7fe7}", 
                                            index = 1, 
                                            linkData = {
                                                position = Vector2.new(0, 0)
                                            }, 
                                            name = "Origin", 
                                            props = {
                                                duration = 1
                                            }, 
                                            state = {
                                                length = 1, 
                                                timePositionNormalized = 0
                                            }, 
                                            weight = 0
                                        }, 
                                        [2] = {
                                            children = {}, 
                                            className = "ClipLayer", 
                                            id = "{6556d92c-2ab0-47f6-9633-1e8b22e8c823}", 
                                            index = 2, 
                                            linkData = {
                                                position = Vector2.new(1, 0)
                                            }, 
                                            name = "Right Walk", 
                                            props = {
                                                animationId = "rbxassetid://10847107747", 
                                                didLoopEventName = "", 
                                                endTime = 1e999, 
                                                looping = -1, 
                                                markerEvents = {}, 
                                                preload = true, 
                                                speed = 1, 
                                                startTime = 0, 
                                                timePositionEvents = {}
                                            }, 
                                            state = {
                                                currentAnimationId = "rbxassetid://10847107747", 
                                                length = 0.625, 
                                                loadingState = "Loaded", 
                                                markerEvents = {}, 
                                                timePosition = 0, 
                                                timePositionEvents = {}, 
                                                timePositionNormalized = 0
                                            }, 
                                            weight = 0
                                        }, 
                                        [3] = {
                                            children = {}, 
                                            className = "ClipLayer", 
                                            id = "{782abac9-1ad8-46b8-9441-dd901a6e923f}", 
                                            index = 3, 
                                            linkData = {
                                                position = Vector2.new(2, 0)
                                            }, 
                                            name = "Right Run", 
                                            props = {
                                                animationId = "rbxassetid://10847291554", 
                                                didLoopEventName = "", 
                                                endTime = 1e999, 
                                                looping = -1, 
                                                markerEvents = {}, 
                                                preload = true, 
                                                speed = 1, 
                                                startTime = 0, 
                                                timePositionEvents = {}
                                            }, 
                                            state = {
                                                currentAnimationId = "rbxassetid://10847291554", 
                                                length = 0.625, 
                                                loadingState = "Loaded", 
                                                markerEvents = {}, 
                                                timePosition = 0, 
                                                timePositionEvents = {}, 
                                                timePositionNormalized = 0
                                            }, 
                                            weight = 0
                                        }, 
                                        [4] = {
                                            children = {}, 
                                            className = "ClipLayer", 
                                            id = "{816c6077-957c-4748-9ed6-72985a98a8af}", 
                                            index = 4, 
                                            linkData = {
                                                position = Vector2.new(-1, 0)
                                            }, 
                                            name = "Left Walk", 
                                            props = {
                                                animationId = "rbxassetid://10382771806", 
                                                didLoopEventName = "", 
                                                endTime = 1e999, 
                                                looping = -1, 
                                                markerEvents = {}, 
                                                preload = true, 
                                                speed = 1, 
                                                startTime = 0, 
                                                timePositionEvents = {}
                                            }, 
                                            state = {
                                                currentAnimationId = "rbxassetid://10382771806", 
                                                length = 0.625, 
                                                loadingState = "Loaded", 
                                                markerEvents = {}, 
                                                timePosition = 0, 
                                                timePositionEvents = {}, 
                                                timePositionNormalized = 0
                                            }, 
                                            weight = 0
                                        }, 
                                        [5] = {
                                            children = {}, 
                                            className = "ClipLayer", 
                                            id = "{9a4dc8c8-59ec-40a8-88ae-36d8c2e7476d}", 
                                            index = 5, 
                                            linkData = {
                                                position = Vector2.new(-2, 0)
                                            }, 
                                            name = "Left Run", 
                                            props = {
                                                animationId = "rbxassetid://10847298457", 
                                                didLoopEventName = "", 
                                                endTime = 1e999, 
                                                looping = -1, 
                                                markerEvents = {}, 
                                                preload = true, 
                                                speed = 1, 
                                                startTime = 0, 
                                                timePositionEvents = {}
                                            }, 
                                            state = {
                                                currentAnimationId = "rbxassetid://10847298457", 
                                                length = 0.625, 
                                                loadingState = "Loaded", 
                                                markerEvents = {}, 
                                                timePosition = 0, 
                                                timePositionEvents = {}, 
                                                timePositionNormalized = 0
                                            }, 
                                            weight = 0
                                        }, 
                                        [6] = {
                                            children = {}, 
                                            className = "ClipLayer", 
                                            id = "{ae2f3459-80bc-4487-a5fb-7b82c38f2f8d}", 
                                            index = 6, 
                                            linkData = {
                                                position = Vector2.new(0, -1)
                                            }, 
                                            name = "Backward Walk", 
                                            props = {
                                                animationId = "rbxassetid://10358505520", 
                                                didLoopEventName = "", 
                                                endTime = 1e999, 
                                                looping = -1, 
                                                markerEvents = {}, 
                                                preload = true, 
                                                speed = 1, 
                                                startTime = 0, 
                                                timePositionEvents = {}
                                            }, 
                                            state = {
                                                currentAnimationId = "rbxassetid://10358505520", 
                                                length = 0.625, 
                                                loadingState = "Loaded", 
                                                markerEvents = {}, 
                                                timePosition = 0, 
                                                timePositionEvents = {}, 
                                                timePositionNormalized = 0
                                            }, 
                                            weight = 0
                                        }, 
                                        [7] = {
                                            children = {}, 
                                            className = "ClipLayer", 
                                            id = "{c6b01432-2acf-4e04-bca4-ecee93647ac6}", 
                                            index = 7, 
                                            linkData = {
                                                position = Vector2.new(0, -2)
                                            }, 
                                            name = "Backward Run", 
                                            props = {
                                                animationId = "rbxassetid://10358526981", 
                                                didLoopEventName = "", 
                                                endTime = 1e999, 
                                                looping = -1, 
                                                markerEvents = {}, 
                                                preload = true, 
                                                speed = 1, 
                                                startTime = 0, 
                                                timePositionEvents = {}
                                            }, 
                                            state = {
                                                currentAnimationId = "rbxassetid://10358526981", 
                                                length = 0.625, 
                                                loadingState = "Loaded", 
                                                markerEvents = {}, 
                                                timePosition = 0, 
                                                timePositionEvents = {}, 
                                                timePositionNormalized = 0
                                            }, 
                                            weight = 0
                                        }, 
                                        [8] = {
                                            children = {}, 
                                            className = "ClipLayer", 
                                            id = "{e466dbc1-f3d2-4271-8ad8-e0ac692c1356}", 
                                            index = 8, 
                                            linkData = {
                                                position = Vector2.new(-0.707106769, -0.707106769)
                                            }, 
                                            name = "Backward Left Walk", 
                                            props = {
                                                animationId = "rbxassetid://10382771806", 
                                                didLoopEventName = "", 
                                                endTime = 1e999, 
                                                looping = -1, 
                                                markerEvents = {}, 
                                                preload = true, 
                                                speed = 1, 
                                                startTime = 0, 
                                                timePositionEvents = {}
                                            }, 
                                            state = {
                                                currentAnimationId = "rbxassetid://10382771806", 
                                                length = 0.625, 
                                                loadingState = "Loaded", 
                                                markerEvents = {}, 
                                                timePosition = 0, 
                                                timePositionEvents = {}, 
                                                timePositionNormalized = 0
                                            }, 
                                            weight = 0
                                        }, 
                                        [9] = {
                                            children = {}, 
                                            className = "ClipLayer", 
                                            id = "{605421b4-16f3-40f9-a781-561ea5fa97fe}", 
                                            index = 9, 
                                            linkData = {
                                                position = Vector2.new(0.707106769, -0.707106769)
                                            }, 
                                            name = "Backward Right Walk", 
                                            props = {
                                                animationId = "rbxassetid://10382635795", 
                                                didLoopEventName = "", 
                                                endTime = 1e999, 
                                                looping = -1, 
                                                markerEvents = {}, 
                                                preload = true, 
                                                speed = 1, 
                                                startTime = 0, 
                                                timePositionEvents = {}
                                            }, 
                                            state = {
                                                currentAnimationId = "rbxassetid://10382635795", 
                                                length = 0.625, 
                                                loadingState = "Loaded", 
                                                markerEvents = {}, 
                                                timePosition = 0, 
                                                timePositionEvents = {}, 
                                                timePositionNormalized = 0
                                            }, 
                                            weight = 0
                                        }, 
                                        [10] = {
                                            children = {}, 
                                            className = "ClipLayer", 
                                            id = "{3f08126d-f7f8-405e-bc24-026900d76dc4}", 
                                            index = 10, 
                                            linkData = {
                                                position = Vector2.new(-1.41421354, -1.41421354)
                                            }, 
                                            name = "Backward Left Run", 
                                            props = {
                                                animationId = "rbxassetid://10382960556", 
                                                didLoopEventName = "", 
                                                endTime = 1e999, 
                                                looping = -1, 
                                                markerEvents = {}, 
                                                preload = true, 
                                                speed = 1, 
                                                startTime = 0, 
                                                timePositionEvents = {}
                                            }, 
                                            state = {
                                                currentAnimationId = "rbxassetid://10382960556", 
                                                length = 0.625, 
                                                loadingState = "Loaded", 
                                                markerEvents = {}, 
                                                timePosition = 0, 
                                                timePositionEvents = {}, 
                                                timePositionNormalized = 0
                                            }, 
                                            weight = 0
                                        }, 
                                        [11] = {
                                            children = {}, 
                                            className = "ClipLayer", 
                                            id = "{bf7bf7ee-c275-4ac6-aa71-86df90705fee}", 
                                            index = 11, 
                                            linkData = {
                                                position = Vector2.new(1.41421354, -1.41421354)
                                            }, 
                                            name = "Backward Right Run", 
                                            props = {
                                                animationId = "rbxassetid://10382949241", 
                                                didLoopEventName = "", 
                                                endTime = 1e999, 
                                                looping = -1, 
                                                markerEvents = {}, 
                                                preload = true, 
                                                speed = 1, 
                                                startTime = 0, 
                                                timePositionEvents = {}
                                            }, 
                                            state = {
                                                currentAnimationId = "rbxassetid://10382949241", 
                                                length = 0.625, 
                                                loadingState = "Loaded", 
                                                markerEvents = {}, 
                                                timePosition = 0, 
                                                timePositionEvents = {}, 
                                                timePositionNormalized = 0
                                            }, 
                                            weight = 0
                                        }
                                    }, 
                                    className = "BlendSpace", 
                                    id = "{01378bfa-3123-4277-be55-5105e62f22f2}", 
                                    linkData = {
                                        [1] = "LocomotingBackward"
                                    }, 
                                    name = "Backward Locomotion", 
                                    props = {
                                        blendSpaceType = "Locomotion", 
                                        lowLodThreshold = 2, 
                                        positionSmoothingTime = 0, 
                                        speed = 0, 
                                        targetPosition = Vector2.new(0, 0)
                                    }, 
                                    state = {
                                        length = 0, 
                                        timePositionNormalized = 0
                                    }, 
                                    weight = 0
                                }, 
                                [2] = {
                                    children = {}, 
                                    className = "ClipLayer", 
                                    id = "{67afe536-0b3e-4542-b392-26a3e7691d57}", 
                                    linkData = {
                                        [1] = "Climbing"
                                    }, 
                                    name = "Climbing", 
                                    props = {
                                        animationId = "rbxassetid://507765644", 
                                        didLoopEventName = "", 
                                        endTime = 1e999, 
                                        looping = -1, 
                                        markerEvents = {}, 
                                        preload = true, 
                                        speed = 0, 
                                        startTime = 0, 
                                        timePositionEvents = {}
                                    }, 
                                    state = {
                                        currentAnimationId = "rbxassetid://507765644", 
                                        length = 1.0416749715805054, 
                                        loadingState = "Loaded", 
                                        markerEvents = {}, 
                                        timePosition = 0, 
                                        timePositionEvents = {}, 
                                        timePositionNormalized = 0
                                    }, 
                                    weight = 0
                                }, 
                                [3] = {
                                    children = {}, 
                                    className = "ClipLayer", 
                                    id = "{4fee757f-9545-47de-9d1b-832f0de17068}", 
                                    linkData = {
                                        [1] = "Emote"
                                    }, 
                                    name = "Emote", 
                                    props = {
                                        didLoopEventName = "", 
                                        endTime = 1e999, 
                                        looping = -1, 
                                        markerEvents = {}, 
                                        preload = true, 
                                        speed = 1, 
                                        startTime = 0, 
                                        timePositionEvents = {
                                            [1] = {
                                                name = "EmoteEnding", 
                                                shouldFireFn = function() --[[ Line: 439 ]] --[[ Name: shouldFireFn ]]

                                                end, 
                                                timePosition = -0.2
                                            }
                                        }
                                    }, 
                                    state = {
                                        length = 0, 
                                        loadingState = "Unloaded", 
                                        markerEvents = {}, 
                                        timePosition = 0, 
                                        timePositionEvents = {}, 
                                        timePositionNormalized = 0
                                    }, 
                                    weight = 0
                                }, 
                                [4] = {
                                    children = {}, 
                                    className = "ClipLayer", 
                                    id = "{65f0fdf6-733e-42b8-b8a1-19ef18c415c1}", 
                                    linkData = {
                                        [1] = "Falling"
                                    }, 
                                    name = "Falling", 
                                    props = {
                                        animationId = "rbxassetid://10921262864", 
                                        didLoopEventName = "", 
                                        endTime = 1e999, 
                                        looping = -1, 
                                        markerEvents = {}, 
                                        preload = true, 
                                        speed = 1, 
                                        startTime = 0, 
                                        timePositionEvents = {}
                                    }, 
                                    state = {
                                        currentAnimationId = "rbxassetid://10921262864", 
                                        length = 0.75, 
                                        loadingState = "Loaded", 
                                        markerEvents = {}, 
                                        timePosition = 0, 
                                        timePositionEvents = {}, 
                                        timePositionNormalized = 0
                                    }, 
                                    weight = 0
                                }, 
                                [5] = {
                                    children = {
                                        [1] = {
                                            children = {}, 
                                            className = "RestPose", 
                                            id = "{3ccee2e5-24c1-46eb-a736-825584054a59}", 
                                            index = 1, 
                                            linkData = {
                                                position = Vector2.new(0, 0)
                                            }, 
                                            name = "Origin", 
                                            props = {
                                                duration = 1
                                            }, 
                                            state = {
                                                length = 1, 
                                                timePositionNormalized = 0
                                            }, 
                                            weight = 0
                                        }, 
                                        [2] = {
                                            children = {}, 
                                            className = "ClipLayer", 
                                            id = "{65ac6017-a983-4124-b6b3-558227f7e545}", 
                                            index = 2, 
                                            linkData = {
                                                position = Vector2.new(0, 1)
                                            }, 
                                            name = "Forward Walk", 
                                            props = {
                                                animationId = "rbxassetid://14045085169", 
                                                didLoopEventName = "", 
                                                endTime = 1e999, 
                                                looping = -1, 
                                                markerEvents = {
                                                    Footstep = "Footstep"
                                                }, 
                                                preload = true, 
                                                speed = 1, 
                                                startTime = 0, 
                                                timePositionEvents = {}
                                            }, 
                                            state = {
                                                currentAnimationId = "rbxassetid://14045085169", 
                                                length = 0, 
                                                loadingState = "Loading", 
                                                markerEvents = {}, 
                                                timePosition = 0, 
                                                timePositionEvents = {}, 
                                                timePositionNormalized = 0
                                            }, 
                                            weight = 0
                                        }, 
                                        [3] = {
                                            children = {}, 
                                            className = "ClipLayer", 
                                            id = "{1d71c8d7-85ee-4ecf-9c9f-aef68c69a889}", 
                                            index = 3, 
                                            linkData = {
                                                position = Vector2.new(0, 2)
                                            }, 
                                            name = "Forward Run", 
                                            props = {
                                                animationId = "rbxassetid://10899968825", 
                                                didLoopEventName = "", 
                                                endTime = 1e999, 
                                                looping = -1, 
                                                markerEvents = {}, 
                                                preload = true, 
                                                speed = 1, 
                                                startTime = 0, 
                                                timePositionEvents = {}
                                            }, 
                                            state = {
                                                currentAnimationId = "rbxassetid://10899968825", 
                                                length = 0.625, 
                                                loadingState = "Loaded", 
                                                markerEvents = {}, 
                                                timePosition = 0, 
                                                timePositionEvents = {}, 
                                                timePositionNormalized = 0
                                            }, 
                                            weight = 0
                                        }, 
                                        [4] = {
                                            children = {}, 
                                            className = "ClipLayer", 
                                            id = "{4512dbbc-91da-45cc-950a-9480266b4b2d}", 
                                            index = 4, 
                                            linkData = {
                                                position = Vector2.new(1, 0)
                                            }, 
                                            name = "Right Walk", 
                                            props = {
                                                animationId = "rbxassetid://10404404615", 
                                                didLoopEventName = "", 
                                                endTime = 1e999, 
                                                looping = -1, 
                                                markerEvents = {}, 
                                                preload = true, 
                                                speed = 1, 
                                                startTime = 0, 
                                                timePositionEvents = {}
                                            }, 
                                            state = {
                                                currentAnimationId = "rbxassetid://10404404615", 
                                                length = 0.625, 
                                                loadingState = "Loaded", 
                                                markerEvents = {}, 
                                                timePosition = 0, 
                                                timePositionEvents = {}, 
                                                timePositionNormalized = 0
                                            }, 
                                            weight = 0
                                        }, 
                                        [5] = {
                                            children = {}, 
                                            className = "ClipLayer", 
                                            id = "{6d769e3c-82cf-4869-a72f-71c8138a1f52}", 
                                            index = 5, 
                                            linkData = {
                                                position = Vector2.new(2, 0)
                                            }, 
                                            name = "Right Run", 
                                            props = {
                                                animationId = "rbxassetid://10404627994", 
                                                didLoopEventName = "", 
                                                endTime = 1e999, 
                                                looping = -1, 
                                                markerEvents = {}, 
                                                preload = true, 
                                                speed = 1, 
                                                startTime = 0, 
                                                timePositionEvents = {}
                                            }, 
                                            state = {
                                                currentAnimationId = "rbxassetid://10404627994", 
                                                length = 0.625, 
                                                loadingState = "Loaded", 
                                                markerEvents = {}, 
                                                timePosition = 0, 
                                                timePositionEvents = {}, 
                                                timePositionNormalized = 0
                                            }, 
                                            weight = 0
                                        }, 
                                        [6] = {
                                            children = {}, 
                                            className = "ClipLayer", 
                                            id = "{0fc10906-5cea-4e87-84e7-053506e27dbf}", 
                                            index = 6, 
                                            linkData = {
                                                position = Vector2.new(-1, 0)
                                            }, 
                                            name = "Left Walk", 
                                            props = {
                                                animationId = "rbxassetid://10404377900", 
                                                didLoopEventName = "", 
                                                endTime = 1e999, 
                                                looping = -1, 
                                                markerEvents = {}, 
                                                preload = true, 
                                                speed = 1, 
                                                startTime = 0, 
                                                timePositionEvents = {}
                                            }, 
                                            state = {
                                                currentAnimationId = "rbxassetid://10404377900", 
                                                length = 0.625, 
                                                loadingState = "Loaded", 
                                                markerEvents = {}, 
                                                timePosition = 0, 
                                                timePositionEvents = {}, 
                                                timePositionNormalized = 0
                                            }, 
                                            weight = 0
                                        }, 
                                        [7] = {
                                            children = {}, 
                                            className = "ClipLayer", 
                                            id = "{5f721a47-53cc-4b3b-bc5b-ea223561ebad}", 
                                            index = 7, 
                                            linkData = {
                                                position = Vector2.new(-2, 0)
                                            }, 
                                            name = "Left Run", 
                                            props = {
                                                animationId = "rbxassetid://10404604071", 
                                                didLoopEventName = "", 
                                                endTime = 1e999, 
                                                looping = -1, 
                                                markerEvents = {}, 
                                                preload = true, 
                                                speed = 1, 
                                                startTime = 0, 
                                                timePositionEvents = {}
                                            }, 
                                            state = {
                                                currentAnimationId = "rbxassetid://10404604071", 
                                                length = 0.625, 
                                                loadingState = "Loaded", 
                                                markerEvents = {}, 
                                                timePosition = 0, 
                                                timePositionEvents = {}, 
                                                timePositionNormalized = 0
                                            }, 
                                            weight = 0
                                        }, 
                                        [8] = {
                                            children = {}, 
                                            className = "ClipLayer", 
                                            id = "{1b1a8b55-c2dc-44bb-999e-eda4f884bd02}", 
                                            index = 8, 
                                            linkData = {
                                                position = Vector2.new(0.707106769, 0.707106769)
                                            }, 
                                            name = "Forward Right Walk", 
                                            props = {
                                                animationId = "rbxassetid://10404269576", 
                                                didLoopEventName = "", 
                                                endTime = 1e999, 
                                                looping = -1, 
                                                markerEvents = {}, 
                                                preload = true, 
                                                speed = 1, 
                                                startTime = 0, 
                                                timePositionEvents = {}
                                            }, 
                                            state = {
                                                currentAnimationId = "rbxassetid://10404269576", 
                                                length = 0.625, 
                                                loadingState = "Loaded", 
                                                markerEvents = {}, 
                                                timePosition = 0, 
                                                timePositionEvents = {}, 
                                                timePositionNormalized = 0
                                            }, 
                                            weight = 0
                                        }, 
                                        [9] = {
                                            children = {}, 
                                            className = "ClipLayer", 
                                            id = "{3423814e-2fd4-4926-803f-334847f77a83}", 
                                            index = 9, 
                                            linkData = {
                                                position = Vector2.new(-0.707106769, 0.707106769)
                                            }, 
                                            name = "Forward Left Walk", 
                                            props = {
                                                animationId = "rbxassetid://10404251500", 
                                                didLoopEventName = "", 
                                                endTime = 1e999, 
                                                looping = -1, 
                                                markerEvents = {}, 
                                                preload = true, 
                                                speed = 1, 
                                                startTime = 0, 
                                                timePositionEvents = {}
                                            }, 
                                            state = {
                                                currentAnimationId = "rbxassetid://10404251500", 
                                                length = 0.625, 
                                                loadingState = "Loaded", 
                                                markerEvents = {}, 
                                                timePosition = 0, 
                                                timePositionEvents = {}, 
                                                timePositionNormalized = 0
                                            }, 
                                            weight = 0
                                        }, 
                                        [10] = {
                                            children = {}, 
                                            className = "ClipLayer", 
                                            id = "{d6493c48-d9cd-4368-820b-0d23c25cb833}", 
                                            index = 10, 
                                            linkData = {
                                                position = Vector2.new(1.41421354, 1.41421354)
                                            }, 
                                            name = "Forward Right Run", 
                                            props = {
                                                animationId = "rbxassetid://10319882993", 
                                                didLoopEventName = "", 
                                                endTime = 1e999, 
                                                looping = -1, 
                                                markerEvents = {}, 
                                                preload = true, 
                                                speed = 1, 
                                                startTime = 0, 
                                                timePositionEvents = {}
                                            }, 
                                            state = {
                                                currentAnimationId = "rbxassetid://10319882993", 
                                                length = 0.625, 
                                                loadingState = "Loaded", 
                                                markerEvents = {}, 
                                                timePosition = 0, 
                                                timePositionEvents = {}, 
                                                timePositionNormalized = 0
                                            }, 
                                            weight = 0
                                        }, 
                                        [11] = {
                                            children = {}, 
                                            className = "ClipLayer", 
                                            id = "{117d88c1-9254-4fea-8bb6-47760516fb0f}", 
                                            index = 11, 
                                            linkData = {
                                                position = Vector2.new(-1.41421354, 1.41421354)
                                            }, 
                                            name = "Forward Left Run", 
                                            props = {
                                                animationId = "rbxassetid://10319903622", 
                                                didLoopEventName = "", 
                                                endTime = 1e999, 
                                                looping = -1, 
                                                markerEvents = {}, 
                                                preload = true, 
                                                speed = 1, 
                                                startTime = 0, 
                                                timePositionEvents = {}
                                            }, 
                                            state = {
                                                currentAnimationId = "rbxassetid://10319903622", 
                                                length = 0.625, 
                                                loadingState = "Loaded", 
                                                markerEvents = {}, 
                                                timePosition = 0, 
                                                timePositionEvents = {}, 
                                                timePositionNormalized = 0
                                            }, 
                                            weight = 0
                                        }
                                    }, 
                                    className = "BlendSpace", 
                                    id = "{d4597589-d9c5-47df-b379-71b2f6af05fe}", 
                                    linkData = {
                                        [1] = "LocomotingForward"
                                    }, 
                                    name = "Forward Locomotion", 
                                    props = {
                                        blendSpaceType = "Locomotion", 
                                        lowLodThreshold = 2, 
                                        positionSmoothingTime = 0, 
                                        speed = 0, 
                                        targetPosition = Vector2.new(0, 0)
                                    }, 
                                    state = {
                                        length = 0, 
                                        timePositionNormalized = 0
                                    }, 
                                    weight = 0
                                }, 
                                [6] = {
                                    children = {}, 
                                    className = "ClipLayer", 
                                    id = "{80711aa0-bdf3-49e1-bcdc-a0900eaabf06}", 
                                    linkData = {
                                        [1] = "Idle"
                                    }, 
                                    name = "Idle", 
                                    props = {
                                        animationId = "rbxassetid://10921258489", 
                                        didLoopEventName = "IdleDidLoop", 
                                        endTime = 1e999, 
                                        looping = -1, 
                                        markerEvents = {}, 
                                        preload = true, 
                                        speed = 1, 
                                        startTime = 0, 
                                        timePositionEvents = {}
                                    }, 
                                    state = {
                                        currentAnimationId = "rbxassetid://10921258489", 
                                        length = 10, 
                                        loadingState = "Loaded", 
                                        markerEvents = {}, 
                                        prevTimePosition = 7.241667054127902, 
                                        timePosition = 7.241667054127902, 
                                        timePositionEvents = {}, 
                                        timePositionNormalized = 0.7241667054127902
                                    }, 
                                    weight = 0
                                }, 
                                [7] = {
                                    children = {
                                        [1] = {
                                            children = {}, 
                                            className = "ClipLayer", 
                                            id = "{9e60c31d-cf4e-4b81-bb19-b708becd9515}", 
                                            linkData = {}, 
                                            props = {
                                                animationId = "rbxassetid://10921263860", 
                                                didLoopEventName = "", 
                                                endTime = 1e999, 
                                                looping = -1, 
                                                markerEvents = {}, 
                                                preload = true, 
                                                speed = 1, 
                                                startTime = 0, 
                                                timePositionEvents = {}
                                            }, 
                                            state = {
                                                currentAnimationId = "rbxassetid://10921263860", 
                                                length = 1.0420000553131104, 
                                                loadingState = "Loaded", 
                                                markerEvents = {}, 
                                                timePosition = 0, 
                                                timePositionEvents = {}, 
                                                timePositionNormalized = 0
                                            }, 
                                            weight = 0
                                        }, 
                                        [2] = {
                                            children = {}, 
                                            className = "ClipLayer", 
                                            id = "{b1751c84-f579-489b-8490-0b3251969695}", 
                                            linkData = {}, 
                                            props = {
                                                animationId = "rbxassetid://10921262864", 
                                                didLoopEventName = "", 
                                                endTime = 1e999, 
                                                looping = -1, 
                                                markerEvents = {}, 
                                                preload = true, 
                                                speed = 1, 
                                                startTime = 0, 
                                                timePositionEvents = {}
                                            }, 
                                            state = {
                                                currentAnimationId = "rbxassetid://10921262864", 
                                                length = 0.75, 
                                                loadingState = "Loaded", 
                                                markerEvents = {}, 
                                                timePosition = 0, 
                                                timePositionEvents = {}, 
                                                timePositionNormalized = 0
                                            }, 
                                            weight = 0
                                        }
                                    }, 
                                    className = "SequenceLayer", 
                                    id = "{5d480bf8-4844-4022-9d45-e56af61bf4e5}", 
                                    linkData = {
                                        [1] = "Jumping"
                                    }, 
                                    name = "Jumping Sequence", 
                                    props = {
                                        incrementMode = 1, 
                                        transitionDurationSeconds = 0.25
                                    }, 
                                    state = {}, 
                                    weight = 0
                                }, 
                                [8] = {
                                    children = {}, 
                                    className = "ClipLayer", 
                                    id = "{14ce7080-803b-435f-93ea-4eb438941c29}", 
                                    linkData = {
                                        [1] = "Sitting"
                                    }, 
                                    name = "Sitting", 
                                    props = {
                                        animationId = "rbxassetid://2506281703", 
                                        didLoopEventName = "", 
                                        endTime = 1e999, 
                                        looping = -1, 
                                        markerEvents = {}, 
                                        preload = true, 
                                        speed = 1, 
                                        startTime = 0, 
                                        timePositionEvents = {}
                                    }, 
                                    state = {
                                        currentAnimationId = "rbxassetid://2506281703", 
                                        length = 0.9169999957084656, 
                                        loadingState = "Loaded", 
                                        markerEvents = {}, 
                                        timePosition = 0, 
                                        timePositionEvents = {}, 
                                        timePositionNormalized = 0
                                    }, 
                                    weight = 0
                                }, 
                                [9] = {
                                    children = {}, 
                                    className = "ClipLayer", 
                                    id = "{f8703185-c346-4a94-94a5-438a9d9b53f4}", 
                                    linkData = {
                                        [1] = "Swimming"
                                    }, 
                                    name = "Swimming", 
                                    props = {
                                        animationId = "rbxassetid://10921264784", 
                                        didLoopEventName = "", 
                                        endTime = 1e999, 
                                        looping = -1, 
                                        markerEvents = {}, 
                                        preload = true, 
                                        speed = 0, 
                                        startTime = 0, 
                                        timePositionEvents = {}
                                    }, 
                                    state = {
                                        currentAnimationId = "rbxassetid://10921264784", 
                                        length = 2.25, 
                                        loadingState = "Loaded", 
                                        markerEvents = {}, 
                                        timePosition = 0, 
                                        timePositionEvents = {}, 
                                        timePositionNormalized = 0
                                    }, 
                                    weight = 0
                                }, 
                                [10] = {
                                    children = {}, 
                                    className = "ClipLayer", 
                                    id = "{85ce8c33-0a03-425b-a7f4-8749f4ef200d}", 
                                    linkData = {
                                        [1] = "SwimmingIdle"
                                    }, 
                                    name = "Swimming Idle", 
                                    props = {
                                        animationId = "rbxassetid://10921265698", 
                                        didLoopEventName = "", 
                                        endTime = 1e999, 
                                        looping = -1, 
                                        markerEvents = {}, 
                                        preload = true, 
                                        speed = 1, 
                                        startTime = 0, 
                                        timePositionEvents = {}
                                    }, 
                                    state = {
                                        currentAnimationId = "rbxassetid://10921265698", 
                                        length = 2.875, 
                                        loadingState = "Loaded", 
                                        markerEvents = {}, 
                                        timePosition = 0, 
                                        timePositionEvents = {}, 
                                        timePositionNormalized = 0
                                    }, 
                                    weight = 0
                                }
                            }, 
                            className = "SelectLayer", 
                            id = "{c77cf2a9-8984-419f-b208-f4a337c63839}", 
                            props = {
                                lowLodThreshold = 3, 
                                selection = "Idle", 
                                transitionDurationSeconds = 0.2
                            }, 
                            state = {}, 
                            weight = 1
                        }
                    }, 
                    className = "Priority", 
                    id = "{54b88a48-a872-4b81-ae19-e530bce87fb3}", 
                    name = "Priority Blend", 
                    props = {
                        fadeDurationSeconds = 0.15
                    }, 
                    state = {
                        easedWeights = {}, 
                        weights = {
                            [1] = 1, 
                            [2] = 0
                        }
                    }, 
                    weight = 1
                }
            }, 
            className = "HeadRotate", 
            id = "{0fd9dd90-1937-4662-85de-fa87000f549e}", 
            name = "Head Rotation", 
            props = {}, 
            state = {}, 
            weight = 1
        }
    }, 
    id = "foo", 
    hrpCFrame = CFrame.new(-4.98748732, 4.45460129, 0.635853291, 1, 0, 0, 0, 1, 0, 0, 0, 1), 
    name = "Parraing", 
    timestamp = 7.241667054127902
};