return {
    DeviceImage = {
        type = "Background", 
        srcDark = "rbxasset://textures/ControlsEmulator/Playstation5_Dark.png", 
        srcLight = "rbxasset://textures/ControlsEmulator/Playstation5_Light.png"
    }, 
    ThumbstickLeft = {
        keyCode = Enum.KeyCode.Thumbstick1, 
        type = "Thumbstick", 
        Position = UDim2.new(0.347, 0, 0.645, 0), 
        relativeStickSize = 0.38, 
        relativeSocketSize = 0.22
    }, 
    ThumbstickLeftMappings = {
        upKeyName = "L Thumbstick Up", 
        downKeyName = "L Thumbstick Down", 
        leftKeyName = "L Thumbstick Left", 
        rightKeyName = "L Thumbstick Right", 
        centerKeyName = "L Thumbstick Click", 
        type = "CrossLayoutMappings", 
        side = "Left", 
        Position = UDim2.new(0.05, 0, 0.818, 0), 
        arrowDestination = UDim2.new(0.34, 0, 0.657, 0), 
        arrowBendPoint = 0.6
    }, 
    ThumbstickRight = {
        keyCode = Enum.KeyCode.Thumbstick2, 
        type = "Thumbstick", 
        Position = UDim2.new(0.6575, 0, 0.645, 0), 
        relativeStickSize = 0.38, 
        relativeSocketSize = 0.22
    }, 
    ThumbstickRightMappings = {
        upKeyName = "R Thumbstick Up", 
        downKeyName = "R Thumbstick Down", 
        leftKeyName = "R Thumbstick Left", 
        rightKeyName = "R Thumbstick Right", 
        centerKeyName = "R Thumbstick Click", 
        type = "CrossLayoutMappings", 
        side = "Right", 
        Position = UDim2.new(0.95, 0, 0.818, 0), 
        arrowDestination = UDim2.new(0.668, 0, 0.657, 0), 
        arrowBendPoint = 0.6
    }, 
    ArrowUp = {
        keyCode = Enum.KeyCode.DPadUp, 
        type = "Button", 
        Position = UDim2.new(0.196, 0, 0.47, 0), 
        Size = UDim2.new(0.035, 0, 0.04, 0)
    }, 
    ArrowRight = {
        keyCode = Enum.KeyCode.DPadRight, 
        type = "Button", 
        Position = UDim2.new(0.25, 0, 0.508, 0), 
        Size = UDim2.new(0.04, 0, 0.035, 0)
    }, 
    ArrowDown = {
        keyCode = Enum.KeyCode.DPadDown, 
        type = "Button", 
        Position = UDim2.new(0.196, 0, 0.55, 0), 
        Size = UDim2.new(0.035, 0, 0.04, 0)
    }, 
    ArrowLeft = {
        keyCode = Enum.KeyCode.DPadLeft, 
        type = "Button", 
        Position = UDim2.new(0.145, 0, 0.508, 0), 
        Size = UDim2.new(0.04, 0, 0.035, 0)
    }, 
    ArrowsMappings = {
        upKeyName = "DPad Up", 
        downKeyName = "DPad Down", 
        leftKeyName = "DPad Left", 
        rightKeyName = "DPad Right", 
        type = "CrossLayoutMappings", 
        side = "Left", 
        Position = UDim2.new(-0.01, 0, 0.58, 0), 
        arrowDestination = UDim2.new(0.192, 0, 0.512, 0), 
        arrowBendPoint = 0.7
    }, 
    ButtonX = {
        keyCode = Enum.KeyCode.ButtonX, 
        type = "Button", 
        Position = UDim2.new(0.735, 0, 0.506, 0), 
        Size = UDim2.new(0.046, 0, 0.046, 0)
    }, 
    ButtonY = {
        keyCode = Enum.KeyCode.ButtonY, 
        type = "Button", 
        Position = UDim2.new(0.81, 0, 0.446, 0), 
        Size = UDim2.new(0.046, 0, 0.046, 0)
    }, 
    ButtonB = {
        keyCode = Enum.KeyCode.ButtonB, 
        type = "Button", 
        Position = UDim2.new(0.881, 0, 0.503, 0), 
        Size = UDim2.new(0.046, 0, 0.046, 0)
    }, 
    ButtonA = {
        keyCode = Enum.KeyCode.ButtonA, 
        type = "Button", 
        Position = UDim2.new(0.805, 0, 0.566, 0), 
        Size = UDim2.new(0.046, 0, 0.046, 0)
    }, 
    AbxyMappings = {
        upKeyName = "Y", 
        downKeyName = "A", 
        leftKeyName = "X", 
        rightKeyName = "B", 
        type = "CrossLayoutMappings", 
        side = "Right", 
        Position = UDim2.new(1.02, 0, 0.614, 0), 
        arrowDestination = UDim2.new(0.818, 0, 0.51, 0), 
        arrowBendPoint = 0.5
    }, 
    ButtonSelect = {
        keyCode = Enum.KeyCode.ButtonSelect, 
        type = "Button", 
        Position = UDim2.new(0.27, 0, 0.414, 0), 
        Size = UDim2.new(0.02, 0, 0.04, 0)
    }, 
    ButtonSelectLabel = {
        keyName = "Select", 
        type = "ButtonMapping", 
        side = "Left", 
        Position = UDim2.new(0.01, 0, 0.39, 0), 
        arrowDestination = UDim2.new(0.268, 0, 0.408, 0), 
        arrowBendPoint = 0.8
    }, 
    ButtonStart = {
        keyCode = Enum.KeyCode.ButtonStart, 
        type = "Button", 
        Position = UDim2.new(0.735, 0, 0.414, 0), 
        Size = UDim2.new(0.02, 0, 0.04, 0)
    }, 
    ButtonStartLabel = {
        keyName = "Start", 
        type = "ButtonMapping", 
        side = "Right", 
        Position = UDim2.new(0.99, 0, 0.39, 0), 
        arrowDestination = UDim2.new(0.737, 0, 0.408, 0), 
        arrowBendPoint = 0.8
    }, 
    ButtonL1 = {
        keyCode = Enum.KeyCode.ButtonL1, 
        type = "Button", 
        Position = UDim2.new(0.2, 0, 0.306, 0), 
        Size = UDim2.new(0.11, 0, 0.04, 0)
    }, 
    ButtonL1Label = {
        keyName = "L1", 
        type = "ButtonMapping", 
        side = "Left", 
        Position = UDim2.new(0, 0, 0.302, 0), 
        arrowDestination = UDim2.new(0.157, 0, 0.32, 0), 
        arrowBendPoint = 0.8
    }, 
    ButtonL2 = {
        keyCode = Enum.KeyCode.ButtonL2, 
        type = "Button", 
        Position = UDim2.new(0.212, 0, 0.246, 0), 
        Size = UDim2.new(0.07, 0, 0.03, 0)
    }, 
    ButtonL2Label = {
        keyName = "L2", 
        type = "ButtonMapping", 
        side = "Left", 
        Position = UDim2.new(0.03, 0, 0.215, 0), 
        arrowDestination = UDim2.new(0.212, 0, 0.247, 0), 
        arrowBendPoint = 0.6
    }, 
    TriggerL2 = {
        keyCode = Enum.KeyCode.ButtonL2, 
        type = "Trigger", 
        Position = UDim2.new(0.23299999999999998, 0, 0.07, 0), 
        Size = UDim2.new(0.069, 0, 0.1, 0)
    }, 
    ButtonR1 = {
        keyCode = Enum.KeyCode.ButtonR1, 
        type = "Button", 
        Position = UDim2.new(0.8, 0, 0.306, 0), 
        Size = UDim2.new(0.11, 0, 0.04, 0)
    }, 
    ButtonR1Label = {
        keyName = "R1", 
        type = "ButtonMapping", 
        side = "Right", 
        Position = UDim2.new(1, 0, 0.302, 0), 
        arrowDestination = UDim2.new(0.835, 0, 0.32, 0), 
        arrowBendPoint = 0.8
    }, 
    ButtonR2 = {
        keyCode = Enum.KeyCode.ButtonR2, 
        type = "Button", 
        Position = UDim2.new(0.788, 0, 0.246, 0), 
        Size = UDim2.new(0.07, 0, 0.03, 0)
    }, 
    ButtonR2Label = {
        keyName = "R2", 
        type = "ButtonMapping", 
        side = "Right", 
        Position = UDim2.new(0.97, 0, 0.215, 0), 
        arrowDestination = UDim2.new(0.79, 0, 0.247, 0), 
        arrowBendPoint = 0.6
    }, 
    TriggerR2 = {
        keyCode = Enum.KeyCode.ButtonR2, 
        type = "Trigger", 
        Position = UDim2.new(0.767, 0, 0.07, 0), 
        Size = UDim2.new(0.069, 0, 0.1, 0)
    }
};