return {
    DialogOption = {
        Cancel = "Cancel", 
        Pause = "Pause", 
        Resume = "Resume"
    }, 
    OperationSource = {
        Gizmo = "Gizmo", 
        History = "History"
    }, 
    RaycastType = {
        Active = "Active", 
        Inactive = "Inactive", 
        Pending = "Pending"
    }, 
    PluginAction = {
        Apply = "Apply", 
        CopySelected = "CopySelected", 
        CutSelected = "CutSelected", 
        DeleteSelected = "DeleteSelected", 
        DuplicateSelected = "DuplicateSelected", 
        EditPlane = "EditPlane", 
        PasteSelected = "PasteSelected", 
        Quit = "Quit"
    }, 
    TransformMode = {
        Duplicate = "Duplicate", 
        Import = "Import", 
        Move = "Move", 
        Paste = "Paste", 
        Stamp = "Stamp"
    }, 
    ImageType = {
        Colormap = "Colormap", 
        Heightmap = "Heightmap"
    }
};