local l_script_FirstAncestor_0 = script:FindFirstAncestor("AssetManager");
return require(l_script_FirstAncestor_0.Packages.Framework).Styling.createStyleSheet("AssetManagerLightTheme", {}, {
    ArrowDownIcon = "rbxasset://studio_svg_textures/Shared/Navigation/Light/Standard/ArrowDown.png", 
    ArrowRightIcon = "rbxasset://studio_svg_textures/Shared/Navigation/Light/Standard/ArrowRight.png", 
    ArrowUpIcon = "rbxasset://studio_svg_textures/Shared/Navigation/Light/Standard/ArrowUp.png", 
    CheckmarkIcon = "rbxasset://studio_svg_textures/Lua/Tutorials/Light/Standard/Checkmark.png", 
    ClearIcon = "rbxasset://studio_svg_textures/Shared/InsertableObjects/Light/Standard/Cleanup.png", 
    FilterIcon = "rbxasset://studio_svg_textures/Shared/Utility/Light/Standard/Filter.png", 
    GroupDefaultIcon = "rbxasset://studio_svg_textures/Shared/Utility/Light/Standard/Group.png", 
    GroupLargeDefaultIcon = "rbxasset://studio_svg_textures/Shared/Utility/Light/Large/Group.png", 
    ImportIcon = "rbxasset://studio_svg_textures/Lua/FileSync/Light/Large/Import.png", 
    PlaceholderAssetIcon = "rbxasset://studio_svg_textures/Shared/Placeholder/Light/Standard/Placeholder.png", 
    PlaceholderIcon = "rbxasset://studio_svg_textures/Shared/Placeholder/Light/Standard/Placeholder.png", 
    RefreshIcon = "rbxasset://studio_svg_textures/Lua/FileSync/Light/Standard/Refresh.png", 
    SearchIcon = "rbxasset://studio_svg_textures/Lua/DeveloperFramework/Light/Standard/Search.png", 
    SidebarCollapseIcon = "rbxasset://studio_svg_textures/Lua/SystemArrows/Light/Standard/DoubleChevronLeft.png", 
    SidebarExpandIcon = "rbxasset://studio_svg_textures/Lua/SystemArrows/Light/Standard/DoubleChevronRight.png", 
    SortIcon = "rbxasset://studio_svg_textures/Lua/AssetManager/Light/Standard/Sort.png", 
    UniverseDefaultIcon = "rbxasset://studio_svg_textures/Shared/Placeholder/Light/Standard/Placeholder.png", 
    UniverseLargeDefaultIcon = "rbxasset://studio_svg_textures/Shared/Placeholder/Light/Standard/Placeholder.png", 
    UserDefaultIcon = "rbxasset://studio_svg_textures/Shared/Utility/Light/Standard/User.png", 
    UserLargeDefaultIcon = "rbxasset://studio_svg_textures/Shared/Utility/Light/Large/User.png"
});