local l_Parent_0 = script.Parent.Parent.Parent;
return require(l_Parent_0.Packages.Framework).Styling.createStyleSheet("ActivityHistoryPluginDarkTheme", {}, {
    arrowdownicon = "rbxasset://studio_svg_textures/Shared/Navigation/Dark/Standard/ArrowDown.png", 
    close = "rbxasset://studio_svg_textures/Lua/Tutorials/Dark/Standard/Close.png", 
    filter = "rbxasset://studio_svg_textures/Lua/ActivityHistory/Dark/Standard/Filter.png", 
    filterdisabled = "rbxasset://studio_svg_textures/Lua/ActivityHistory/Dark/Standard/FilterDisabled.png", 
    nofilterresults = "rbxasset://studio_svg_textures/Lua/ActivityHistory/Dark/Large/NoFilterResults.png", 
    threedotsicon = "rbxasset://studio_svg_textures/Shared/Navigation/Dark/Standard/More.png", 
    unsavedexperience = "rbxasset://studio_svg_textures/Lua/ActivityHistory/Dark/Large/UnsavedExperience.png"
});