local l_script_FirstAncestor_0 = script:FindFirstAncestor("AssetManager");
return require(l_script_FirstAncestor_0.Packages.Framework).Styling.createStyleSheet("AssetManagerDarkTheme", {}, {
    ArrowDownIcon = "rbxasset://studio_svg_textures/Shared/Navigation/Dark/Standard/ArrowDown.png", 
    ArrowRightIcon = "rbxasset://studio_svg_textures/Shared/Navigation/Dark/Standard/ArrowRight.png", 
    ArrowUpIcon = "rbxasset://studio_svg_textures/Shared/Navigation/Dark/Standard/ArrowUp.png", 
    CheckmarkIcon = "rbxasset://studio_svg_textures/Lua/Tutorials/Dark/Standard/Checkmark.png", 
    ClearIcon = "rbxasset://studio_svg_textures/Shared/InsertableObjects/Dark/Standard/Cleanup.png", 
    FilterIcon = "rbxasset://studio_svg_textures/Shared/Utility/Dark/Standard/Filter.png", 
    GroupDefaultIcon = "rbxasset://studio_svg_textures/Shared/Utility/Dark/Standard/Group.png", 
    GroupLargeDefaultIcon = "rbxasset://studio_svg_textures/Shared/Utility/Dark/Large/Group.png", 
    ImportIcon = "rbxasset://studio_svg_textures/Lua/FileSync/Dark/Large/Import.png", 
    PlaceholderAssetIcon = "rbxasset://studio_svg_textures/Shared/Placeholder/Dark/Standard/Placeholder.png", 
    PlaceholderIcon = "rbxasset://studio_svg_textures/Shared/Placeholder/Dark/Standard/Placeholder.png", 
    RefreshIcon = "rbxasset://studio_svg_textures/Lua/FileSync/Dark/Standard/Refresh.png", 
    SearchIcon = "rbxasset://studio_svg_textures/Lua/DeveloperFramework/Dark/Standard/Search.png", 
    SidebarCollapseIcon = "rbxasset://studio_svg_textures/Lua/SystemArrows/Dark/Standard/DoubleChevronLeft.png", 
    SidebarExpandIcon = "rbxasset://studio_svg_textures/Lua/SystemArrows/Dark/Standard/DoubleChevronRight.png", 
    SortIcon = "rbxasset://studio_svg_textures/Lua/AssetManager/Dark/Standard/Sort.png", 
    UniverseDefaultIcon = "rbxasset://studio_svg_textures/Shared/Placeholder/Dark/Standard/Placeholder.png", 
    UniverseLargeDefaultIcon = "rbxasset://studio_svg_textures/Shared/Placeholder/Dark/Standard/Placeholder.png", 
    UserDefaultIcon = "rbxasset://studio_svg_textures/Shared/Utility/Dark/Standard/User.png", 
    UserLargeDefaultIcon = "rbxasset://studio_svg_textures/Shared/Utility/Dark/Large/User.png", 
    TestCol = Color3.fromRGB(255, 0, 0)
});