return {
    DeviceImage = {
        type = "Background", 
        srcDark = "rbxasset://textures/ControlsEmulator/Quest3_Dark.png", 
        srcLight = "rbxasset://textures/ControlsEmulator/Quest3_Light.png"
    }, 
    ThumbstickLeft = {
        keyCode = Enum.KeyCode.Thumbstick1, 
        type = "Thumbstick", 
        Position = UDim2.new(0.23, 0, 0.225, 0), 
        relativeStickSize = 0.3, 
        relativeSocketSize = 0.15
    }, 
    ThumbstickLeftMappings = {
        upKeyName = "L Thumbstick Up", 
        downKeyName = "L Thumbstick Down", 
        leftKeyName = "L Thumbstick Left", 
        rightKeyName = "L Thumbstick Right", 
        centerKeyName = "L Thumbstick Click", 
        type = "CrossLayoutMappings", 
        side = "Left", 
        Position = UDim2.new(0, 0, 0.15, 0), 
        arrowDestination = UDim2.new(0.23, 0, 0.225, 0), 
        arrowBendPoint = 0.5
    }, 
    ThumbstickRight = {
        keyCode = Enum.KeyCode.Thumbstick2, 
        type = "Thumbstick", 
        Position = UDim2.new(0.772, 0, 0.225, 0), 
        relativeStickSize = 0.3, 
        relativeSocketSize = 0.15
    }, 
    ThumbstickRightMappings = {
        upKeyName = "R Thumbstick Up", 
        downKeyName = "R Thumbstick Down", 
        leftKeyName = "R Thumbstick Left", 
        rightKeyName = "R Thumbstick Right", 
        centerKeyName = "R Thumbstick Click", 
        type = "CrossLayoutMappings", 
        side = "Right", 
        Position = UDim2.new(1, 0, 0.15, 0), 
        arrowDestination = UDim2.new(0.772, 0, 0.225, 0), 
        arrowBendPoint = 0.6
    }, 
    ButtonX = {
        keyCode = Enum.KeyCode.ButtonX, 
        type = "Button", 
        Position = UDim2.new(0.215, 0, 0.3, 0), 
        Size = UDim2.new(0.046, 0, 0.046, 0)
    }, 
    ButtonXLabel = {
        keyName = "X", 
        type = "ButtonMapping", 
        side = "Left", 
        Position = UDim2.new(0.08, 0, 0.4, 0), 
        arrowDestination = UDim2.new(0.215, 0, 0.318, 0), 
        arrowBendPoint = 1
    }, 
    ButtonY = {
        keyCode = Enum.KeyCode.ButtonY, 
        type = "Button", 
        Position = UDim2.new(0.29, 0, 0.267, 0), 
        Size = UDim2.new(0.046, 0, 0.046, 0)
    }, 
    ButtonYLabel = {
        keyName = "Y", 
        type = "ButtonMapping", 
        side = "Left", 
        Position = UDim2.new(0, 0, 0.79, 0), 
        arrowDestination = UDim2.new(0.29, 0, 0.285, 0), 
        arrowBendPoint = 1
    }, 
    ButtonB = {
        keyCode = Enum.KeyCode.ButtonB, 
        type = "Button", 
        Position = UDim2.new(0.71, 0, 0.27, 0), 
        Size = UDim2.new(0.051, 0, 0.051, 0)
    }, 
    ButtonBLabel = {
        keyName = "B", 
        type = "ButtonMapping", 
        side = "Right", 
        Position = UDim2.new(1, 0, 0.79, 0), 
        arrowDestination = UDim2.new(0.71, 0, 0.288, 0), 
        arrowBendPoint = 1
    }, 
    ButtonA = {
        keyCode = Enum.KeyCode.ButtonA, 
        type = "Button", 
        Position = UDim2.new(0.78, 0, 0.3, 0), 
        Size = UDim2.new(0.046, 0, 0.046, 0)
    }, 
    ButtonALabel = {
        keyName = "A", 
        type = "ButtonMapping", 
        side = "Right", 
        Position = UDim2.new(0.92, 0, 0.4, 0), 
        arrowDestination = UDim2.new(0.78, 0, 0.318, 0), 
        arrowBendPoint = 1
    }, 
    ButtonStart = {
        keyCode = Enum.KeyCode.ButtonStart, 
        type = "Button", 
        Position = UDim2.new(0.165, 0, 0.3, 0), 
        Size = UDim2.new(0.035, 0, 0.035, 0)
    }, 
    ButtonStartLabel = {
        keyName = "Start", 
        type = "ButtonMapping", 
        side = "Left", 
        Position = UDim2.new(0.08, 0, 0.3, 0), 
        arrowDestination = UDim2.new(0.15, 0, 0.3, 0), 
        arrowBendPoint = 0.75
    }, 
    ButtonL1 = {
        keyCode = Enum.KeyCode.ButtonL1, 
        type = "Button", 
        Position = UDim2.new(0.4, 0, 0.33, 0), 
        Size = UDim2.new(0.04, 0, 0.1, 0)
    }, 
    ButtonL1Label = {
        keyName = "L1", 
        type = "ButtonMapping", 
        side = "Left", 
        Position = UDim2.new(0.4, 0, 0.5, 0), 
        arrowDestination = UDim2.new(0.42, 0, 0.35, 0), 
        arrowBendPoint = 1
    }, 
    ButtonL2 = {
        keyCode = Enum.KeyCode.ButtonL2, 
        type = "Button", 
        Position = UDim2.new(0.217, 0, 0.48, 0), 
        Size = UDim2.new(0.12, 0, 0.07, 0)
    }, 
    ButtonL2Label = {
        keyName = "L2", 
        type = "ButtonMapping", 
        side = "Left", 
        Position = UDim2.new(0.05, 0, 0.5, 0), 
        arrowDestination = UDim2.new(0.217, 0, 0.48, 0), 
        arrowBendPoint = 0
    }, 
    TriggerL2 = {
        keyCode = Enum.KeyCode.ButtonL2, 
        type = "Trigger", 
        Position = UDim2.new(0.43, 0, 0.04, 0), 
        Size = UDim2.new(0.069, 0, 0.1, 0)
    }, 
    ButtonR1 = {
        keyCode = Enum.KeyCode.ButtonR1, 
        type = "Button", 
        Position = UDim2.new(0.59, 0, 0.33, 0), 
        Size = UDim2.new(0.04, 0, 0.1, 0)
    }, 
    ButtonR1Label = {
        keyName = "R1", 
        type = "ButtonMapping", 
        side = "Right", 
        Position = UDim2.new(0.595, 0, 0.5, 0), 
        arrowDestination = UDim2.new(0.575, 0, 0.35, 0), 
        arrowBendPoint = 1
    }, 
    ButtonR2 = {
        keyCode = Enum.KeyCode.ButtonR2, 
        type = "Button", 
        Position = UDim2.new(0.788, 0, 0.48, 0), 
        Size = UDim2.new(0.12, 0, 0.07, 0)
    }, 
    ButtonR2Label = {
        keyName = "R2", 
        type = "ButtonMapping", 
        side = "Right", 
        Position = UDim2.new(0.95, 0, 0.5, 0), 
        arrowDestination = UDim2.new(0.788, 0, 0.48, 0), 
        arrowBendPoint = 0.7
    }, 
    TriggerR2 = {
        keyCode = Enum.KeyCode.ButtonR2, 
        type = "Trigger", 
        Position = UDim2.new(0.5700000000000001, 0, 0.04, 0), 
        Size = UDim2.new(0.069, 0, 0.1, 0)
    }
};