local l_script_FirstAncestor_0 = script:FindFirstAncestor("CompositorDebugger");
return require(l_script_FirstAncestor_0.Packages.Framework).Styling.createStyleSheet("CompositorDebuggerLightTheme", {}, {
    InactiveLayer = Color3.fromHex("#989898"), 
    ActiveLayer = Color3.fromHex("#1D1D1D"), 
    LayerHover = Color3.fromHex("#E4EEFE"), 
    ActiveTimeBar = Color3.fromHex("#008BDB"), 
    InactiveTimeBar = Color3.fromHex("#989898"), 
    HistoryLegend1 = Color3.fromHex("#E55681"), 
    HistoryLegend2 = Color3.fromHex("#03AF52"), 
    HistoryLegend3 = Color3.fromHex("#069DD0"), 
    AdornmentDot1 = Color3.fromHex("#C5A349"), 
    AdornmentDot2 = Color3.fromHex("#D97F16"), 
    AdornmentDot3 = Color3.fromHex("#E55681"), 
    AdornmentDot4 = Color3.fromHex("#DD31BE"), 
    AdornmentDot5 = Color3.fromHex("#8E41F1"), 
    AdornmentDot6 = Color3.fromHex("#069DD0"), 
    AdornmentDot7 = Color3.fromHex("#16BF9B"), 
    AdornmentDot8 = Color3.fromHex("#03AF52"), 
    AdornmentDot9 = Color3.fromHex("#6EB200"), 
    AdornmentDot10 = Color3.fromHex("#B2BF03"), 
    AdornmentDot11 = Color3.fromHex("#9E9700")
});