local l_Parent_0 = script.Parent.Parent.Parent;
return require(l_Parent_0.Packages.enumerate)("GenerationErrorType", {
    "None", 
    "Unknown", 
    "CustomMessage", 
    "NoSession", 
    "NoSelectedMaterial", 
    "FailedToGenerateMaps", 
    "TooManyRequests", 
    "ServerError500", 
    "ServerError504", 
    "TextFullyFiltered", 
    "AccountingFailedDecrement", 
    "FailedToSetImage"
});